CREATE TABLE metainfo (
    "table" text,
    "column" text,
    "type" text,
    "references" text,
    "description" text,
    "view" boolean
);

CREATE TABLE usergroups (
    id serial NOT NULL,
    name text
);
COPY usergroups (id, name) FROM stdin;
1	admin
2	producer
3	customer
0	everybody
\.
ALTER TABLE ONLY usergroups
    ADD CONSTRAINT usergroups_pkey PRIMARY KEY (id);
SELECT pg_catalog.setval ('usergroups_id_seq', 4, true);

CREATE TABLE groupabilities (
    id serial NOT NULL,
    usergroup integer,
    ability text,
    "type" text
);
COPY groupabilities (id, usergroup, ability, "type") FROM stdin;
1	0	introspection	abilityAllow
2	0	directory.get	abilityAllow
3	0	directory.set	abilityAllow
4	0	directory.list	abilityAllow
5	0	directory.implementation.get.user	abilityAllow
6	1	list	abilityAllow
7	1	create	abilityAllow
8	1	change	abilityAllow
9	1	delete	abilityAllow
10	1	directory.implementation	abilityAllow
\.
ALTER TABLE ONLY groupabilities
    ADD CONSTRAINT "$1" FOREIGN KEY (usergroup) REFERENCES usergroups(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
SELECT pg_catalog.setval ('groupabilities_id_seq', 36, true);

CREATE TABLE users (
    id serial NOT NULL,
    usergroup integer,
    givenname text,
    surname text,
    username text,
    "password" text,
    address text,
    zipcode text,
    postaddress text,
    email text,
    telephone text,
    mobile text,
    fax text,
    "language" text
);
COPY users (id, usergroup, givenname, surname, username, "password", address, zipcode, postaddress, email, telephone, mobile, fax, "language") FROM stdin;
1	1	Admin	Adminsson	admin	hej	Hopp	05456	Abisko	admin@lansmusiken.net	06453	074372	06536	sv_SE.UTF-8
\.
ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY users
    ADD CONSTRAINT "$1" FOREIGN KEY (usergroup) REFERENCES usergroups(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
SELECT pg_catalog.setval ('users_id_seq', 6, true);

CREATE TABLE userabilities (
    id serial NOT NULL,
    "user" integer,
    ability text,
    "type" text
);
ALTER TABLE ONLY userabilities
    ADD CONSTRAINT userabilities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY userabilities
    ADD CONSTRAINT "$1" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
SELECT pg_catalog.setval ('userabilities_id_seq', 1, false);

COPY metainfo ("table", "column", "type", "references", description, "view") FROM stdin;
usergroups	\N	\N	\N	%(name)s	\N
users	\N	\N	\N	%(username)s (%(givenname)s %(surname)s) in %(usergroup.name)s	\N
metainfo	type	<"Type", [["__builtin__", "object"], ["__builtin__", "type"]]>	Type	\N	\N
usergroups	id	<"Type", [["Grimoire.Utils", "GenericWrapper"], ["Grimoire.Utils", "Wrapper"], ["Grimoire.Types.Derived", "SerialType"]]>	\N	Id	\N
users	id	<"Type", [["Grimoire.Utils", "GenericWrapper"], ["Grimoire.Utils", "Wrapper"], ["Grimoire.Types.Derived", "SerialType"]]>	\N	Id	\N
users	usergroup	<'ReferenceType', 'usergroups')>	usergroups	Group (type of user)	\N
userabilities	id	<"Type", [["Grimoire.Utils", "GenericWrapper"], ["Grimoire.Utils", "Wrapper"], ["Grimoire.Types.Derived", "SerialType"]]>	\N	Id	\N
groupabilities	\N	\N	\N	Ability %(type)s:%(ability)s for user group %(usergroup.name)s	\N
groupabilities	id	<"Type", [["Grimoire.Utils", "GenericWrapper"], ["Grimoire.Utils", "Wrapper"], ["Grimoire.Types.Derived", "SerialType"]]>	\N	Id	\N
groupabilities	usergroup	<'ReferenceType', 'usergroups'>	usergroups	Group	\N
userabilities	user	<'ReferenceType', 'users'>	users	User	\N
userabilities	\N	\N	\N	%(hours)s worked in project %(project.name)s	\N
users	username	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Username	\N
users	password	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Password	\N
users	zipcode	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	ZIP-code	\N
users	email	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	E-mail	\N
users	telephone	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Telephone	\N
users	mobile	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Mobile phone	\N
users	fax	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Fax	\N
users	language	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Preferred language	\N
groupabilities	ability	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Ability	\N
userabilities	ability	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Ability	\N
groupabilities	type	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Type	\N
userabilities	type	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'str']]>, ), '__doc__': None}, ), )>	\N	Type	\N
metainfo	table	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Table	\N
metainfo	column	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Column	\N
metainfo	description	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Description	\N
usergroups	name	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Name	\N
users	givenname	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Given name	\N
users	surname	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Surname	\N
users	address	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Address	\N
users	postaddress	<'Object', (<'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, ('NonemptyType', (<'Type', [['__builtin__', 'object'], ['Grimoire', 'Types', 'Derived', 'GenericGeneratedType'], ['Grimoire', 'Types', 'Derived', 'GenericStaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericDerivedType'], ['Grimoire', 'Types', 'Derived', 'GenericNonemptyType']]>, <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), {'__module__': 'Grimoire.Types.Derived', '__metaclass__': <'Type', [['__builtin__', 'object'], ['__builtin__', 'type'], ['Grimoire', 'Types', 'Derived', 'GeneratedType'], ['Grimoire', 'Types', 'Derived', 'StaticDerivedType'], ['Grimoire', 'Types', 'Derived', 'DerivedType'], ['Grimoire', 'Types', 'Derived', 'NonemptyType']]>, 'parentType': <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, 'tag': ('nonempty', <'Type', [['__builtin__', 'object'], ['__builtin__', 'basestring'], ['__builtin__', 'unicode']]>, ), '__doc__': None}, ), )>	\N	Postal adress	\N
\.
